version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/packages/main"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    versioning-strategy: increase

  - package-ecosystem: "npm"
    directory: "/packages/worker"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "all"
    versioning-strategy: increase
